"""Insitutes changed

Revision ID: 113f13023e9a
Revises: 9a2c08ab93e2
Create Date: 2024-01-13 14:34:33.359519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113f13023e9a'
down_revision: Union[str, None] = '9a2c08ab93e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('institute_university_id_fkey', 'institute', type_='foreignkey')
    op.drop_column('institute', 'university_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institute', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('institute_university_id_fkey', 'institute', 'university', ['university_id'], ['id'])
    # ### end Alembic commands ###
