"""added student pass

Revision ID: 179d6a1f1176
Revises: 26aa5dc95d78
Create Date: 2024-01-11 11:54:05.396336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179d6a1f1176'
down_revision: Union[str, None] = '26aa5dc95d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_tasks', sa.Column('student_pass', sa.Boolean(), nullable=False, default=False,
                                             server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_tasks', 'student_pass')
    # ### end Alembic commands ###
