"""buddy table extended

Revision ID: 25ba9e4a3c54
Revises: 5b2045bdcdaa
Create Date: 2024-01-13 18:38:59.393458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ba9e4a3c54'
down_revision: Union[str, None] = '5b2045bdcdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_buddy', sa.Column('last_arrival', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile_buddy', 'arrival', ['last_arrival'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_buddy', type_='foreignkey')
    op.drop_column('profile_buddy', 'last_arrival')
    # ### end Alembic commands ###
