"""arrival email column added

Revision ID: 28bbfffba3b2
Revises: d5c113558138
Create Date: 2023-11-29 21:57:57.029918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bbfffba3b2'
down_revision: Union[str, None] = 'd5c113558138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival_participants', sa.Column('participant_email', sa.String(length=320), nullable=False))
    op.drop_constraint('arrival_participants_participant_id_fkey', 'arrival_participants', type_='foreignkey')
    op.create_foreign_key(None, 'arrival_participants', 'user', ['participant_email'], ['email'])
    op.drop_column('arrival_participants', 'participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival_participants', sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arrival_participants', type_='foreignkey')
    op.create_foreign_key('arrival_participants_participant_id_fkey', 'arrival_participants', 'user', ['participant_id'], ['id'])
    op.drop_column('arrival_participants', 'participant_email')
    # ### end Alembic commands ###
