"""Added tasks table

Revision ID: 3128d7e1af64
Revises: 91524d50be68
Create Date: 2023-11-08 21:40:43.901701

"""
from typing import Sequence, Union
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3128d7e1af64'
down_revision: Union[str, None] = '91524d50be68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_tasks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('airport_meeting', sa.Boolean(), nullable=False),
    sa.Column('motel_checked_in', sa.Boolean(), nullable=False),
    sa.Column('money_exchange', sa.Boolean(), nullable=False),
    sa.Column('sim_card_created', sa.Boolean(), nullable=False),
    sa.Column('medical_examinated', sa.Boolean(), nullable=False),
    sa.Column('passport_translated', sa.Boolean(), nullable=False),
    sa.Column('bank_card', sa.Boolean(), nullable=False),
    sa.Column('enrollment_documents', sa.Boolean(), nullable=False),
    sa.Column('insurance', sa.Boolean(), nullable=False),
    sa.Column('dormitory_documents', sa.Boolean(), nullable=False),
    sa.Column('student_ID', sa.Boolean(), nullable=False),
    sa.Column('medical_tests', sa.Boolean(), nullable=False),
    sa.Column('visa_extension', sa.Boolean(), nullable=False),
    sa.Column('fingerprinting', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_tasks')
    # ### end Alembic commands ###
