"""tables_related_to_profile_created

Revision ID: 4ad492d95e92
Revises: f173ae0907e8
Create Date: 2023-11-07 18:38:54.459428

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad492d95e92'
down_revision: Union[str, None] = 'f173ae0907e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon_filepath', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institute',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('telegram', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=12), nullable=False),
    sa.Column('vk', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_buddy',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('photo_filepath', sa.String(length=1000), nullable=False),
    sa.Column('full_name', sa.String(length=320), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('native_language', sa.Integer(), nullable=False),
    sa.Column('buddy_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['native_language'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_languages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_student',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('photo_filepath', sa.String(length=1000), nullable=False),
    sa.Column('full_name', sa.String(length=320), nullable=False),
    sa.Column('citizenship', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=6), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('native_language', sa.Integer(), nullable=False),
    sa.Column('university', sa.Integer(), nullable=False),
    sa.Column('escort_paid', sa.Boolean(), nullable=False),
    sa.Column('last_buddy', sa.Integer(), nullable=False),
    sa.Column('institute', sa.Integer(), nullable=False),
    sa.Column('study_program', sa.String(length=100), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('visa_expiration', sa.Date(), nullable=False),
    sa.Column('accommodation', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['citizenship'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institute'], ['institute.id'], ),
    sa.ForeignKeyConstraint(['last_buddy'], ['profile_buddy.id'], ),
    sa.ForeignKeyConstraint(['native_language'], ['language.id'], ),
    sa.ForeignKeyConstraint(['university'], ['university.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_student')
    op.drop_table('user_languages')
    op.drop_table('profile_buddy')
    op.drop_table('contacts')
    op.drop_table('institute')
    op.drop_table('language')
    op.drop_table('country')
    # ### end Alembic commands ###
