"""arrival tables added

Revision ID: 4c437151bd58
Revises: 0571857badf7
Create Date: 2023-11-27 22:03:42.607485

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c437151bd58'
down_revision: Union[str, None] = '0571857badf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrival',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=100), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('arrival_point', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('tickets', sa.String(length=1000), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrival_participants',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('arrival_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('participant_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['participant_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrival_participants')
    op.drop_table('arrival')
    # ### end Alembic commands ###
