"""tables changes

Revision ID: 7cb1ec83df46
Revises: c72b511845db
Create Date: 2023-11-09 17:00:57.815209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb1ec83df46'
down_revision: Union[str, None] = 'c72b511845db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('contacts', 'telegram',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contacts', 'whatsapp',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('contacts', 'vk',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'vk',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contacts', 'whatsapp',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('contacts', 'telegram',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
