"""arrival invitations table added

Revision ID: a00594eab8a1
Revises: 28bbfffba3b2
Create Date: 2023-12-09 18:42:31.110122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00594eab8a1'
down_revision: Union[str, None] = '28bbfffba3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrival_invitations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('arrival_id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['student_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrival_invitations')
    # ### end Alembic commands ###
