"""chats and messages

Revision ID: a6c10ea79bb3
Revises: dc6f77aa4a0d
Create Date: 2023-12-25 18:18:56.945631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c10ea79bb3'
down_revision: Union[str, None] = 'dc6f77aa4a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
