"""tables changes

Revision ID: c72b511845db
Revises: 3128d7e1af64
Create Date: 2023-11-09 16:56:41.721264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72b511845db'
down_revision: Union[str, None] = '3128d7e1af64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_buddy', 'photo_filepath',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('profile_buddy', 'full_name',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('profile_buddy', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profile_buddy', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profile_buddy', 'native_language',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'photo_filepath',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('profile_student', 'full_name',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('profile_student', 'citizenship',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'sex',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('profile_student', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profile_student', 'native_language',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'university',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'last_buddy',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'institute',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_student', 'study_program',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profile_student', 'arrival_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profile_student', 'visa_expiration',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profile_student', 'accommodation',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('profile_student', 'comment',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_student', 'comment',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('profile_student', 'accommodation',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('profile_student', 'visa_expiration',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profile_student', 'arrival_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profile_student', 'study_program',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profile_student', 'institute',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_student', 'last_buddy',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_student', 'university',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_student', 'native_language',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_student', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profile_student', 'sex',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('profile_student', 'citizenship',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_student', 'full_name',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('profile_student', 'photo_filepath',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('profile_buddy', 'native_language',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_buddy', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profile_buddy', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profile_buddy', 'full_name',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('profile_buddy', 'photo_filepath',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
