"""buddy table extended

Revision ID: ceef27659b6a
Revises: 25ba9e4a3c54
Create Date: 2024-01-13 19:22:33.211526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceef27659b6a'
down_revision: Union[str, None] = '25ba9e4a3c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_buddy_last_arrival_fkey', 'profile_buddy', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('profile_buddy_last_arrival_fkey', 'profile_buddy', 'arrival', ['last_arrival'], ['id'])
    # ### end Alembic commands ###
