"""token_table_changed

Revision ID: d01a0007eb3e
Revises: cc20ca2efdc3
Create Date: 2023-11-02 14:53:24.947963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01a0007eb3e'
down_revision: Union[str, None] = 'cc20ca2efdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
