"""email_verified_column_added

Revision ID: e0dfe00f8e1c
Revises: 02d8e2de6bb1
Create Date: 2023-10-29 17:49:28.658457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dfe00f8e1c'
down_revision: Union[str, None] = '02d8e2de6bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
